### ISSUE TITLE
Sketch Measure 2.7.7 doesn't work with Sketch 51.3

### ISSUE THREAD

**Issue by cheics-d2l** [utom/sketch-measure#532]
![image](https://user-images.githubusercontent.com/8430763/51406833-41514e00-1b28-11e9-92c5-95a41b0e1887.png)

I get the following errors in the console trying to dimension things.

```
Exception: TypeError: sharedStyles.addSharedStyleWithName_firstInstance is not a function. (In 'sharedStyles.addSharedStyleWithName_firstInstance(name, style)', 'sharedStyles.addSharedStyleWithName_firstInstance' is undefined)
```

```
TypeError: sharedStyles.addSharedStyleWithName_firstInstance is not a function. (In 'sharedStyles.addSharedStyleWithName_firstInstance(name, style)', 'sharedStyles.addSharedStyleWithName_firstInstance' is undefined)
line: 661
sourceURL: /Users/cheics/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript
column: 62
stack: sharedLayerStyle@/Users/cheics/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript:661:62
liteSizes@/Users/cheics/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript:1816:45
init@/Users/cheics/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript:80:39
commandSizes@/Users/cheics/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript<…>
```

**Comment by MIkeeJY** [comment]
You can use 2.7.5
