### ISSUE TITLE
Plugin not working (Sketch 51.3 & MacOS Sierra)

### ISSUE THREAD

**Issue by utesahara1893** [utom/sketch-measure#599]
Hey, my plugin doesn't work. I'm using the old version 51.3, my licence expired just today and I can't update the whole Sketch. The plugin I'm using is version 2.7.7. I followed the known instructions (uninstall, quit Sketch, empty the plugin cache, reinstall) but it's not working either. The progress bar freezes right at the start, nothing happens. I tried the newest fork version, but its not working tho.

What can I do? I have to export my design files for the programmer, but in this case I can't do it without listing all the design specs manually. Thats pretty annoying.

Thanks in advance.

**Comment by idsampaio** [comment]
@utesahara1893  The plugin is working on Sketch version 56.3 with plugin version 2.8.0, uninstall it, and install it again here: https://github.com/ellunium/sketch-measure-latest

**Comment by utesahara1893** [comment]
Hey. No, its not working. I followed your instructions, uninstalled the plugin and installed version 2.8.0, now the plugin doesn't hangs on the start of the spec export, it shows a error message when starting the export.

**Comment by utesahara1893** [comment]
It says: 

Error: layer.sharedStyleID is not a function. (In 'layer.sharedStyleID()', 'layer.sharedStyleID' is undefined)
